ci: Change CI workflow
Growthers/enshita pull request #106
Opened 2022-08-21 14:28 UTC by re-taro

The naming convention is as follows...
client-\*.yml (for client)
server-\*.yml (for server)

Refs: https://github.com/Growthers/enshita/issues/102

2022-08-21 14:44 UTC, re-taro commented
#108 のあとにマージされます

2022-08-21 15:08 UTC, mirror-kt requested changes
reviewing...

2022-08-21 15:22 UTC, mirror-kt requested changes
`.github/workflows/client-fmt.yml` に一例を示しました。
他のワークフローも同様にステータスチェック用のjobを分けることでifの記述回数を減らすことができ、リーダビリティが上がります

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +        if: steps.changes.outputs.client == 'true'
```suggestion
```

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +        if: steps.changes.outputs.client == 'true'
```suggestion
```

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +        if: steps.changes.outputs.client == 'true'
以降も同様にstepレベルでのif分岐は必要ないです

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    if: steps.changes.outputs.client == 'true'
```

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
jobレベルでif分岐を行うことで、各stepでifを書く必要がなくなります

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    run-formatter-check:
        if: ${{ ! failure() }}
        needs: run-formatter
        runs-on: ubuntu-latest
        steps:
            - run: echo "Formatter is successfully executed. "
```

2022-08-21 15:22 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
このjobを追加して、Branch ProtectionでのStatus Checkではこちらを指定してください。
`run-formatter` が「失敗しなかったとき」=「成功したとき」or「スキップされたとき」、`run-formatter-check` は成功します。
これにより、フロントのチェックが通っていなくてもバックエンドのPRをマージすることができるようになります。

2022-08-21 15:30 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
このsuggestionを書いたあとに、これをやるためにはpath-filterをそれ単体のjobにする必要が有ることに気づきました…

2022-08-21 15:37 UTC, mirror-kt reviewed
こうかな
なんかインデントがおかしい気もするけどよしなにしてもらって…

2022-08-21 15:37 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +jobs:
```suggestion
jobs:
  front-filter:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ github.token }}
          filters: .github/filters.yml
```

2022-08-21 15:37 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    needs: front-filter
```

2022-08-21 15:38 UTC, mirror-kt commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
https://github.com/Growthers/enshita/pull/106#pullrequestreview-1079688993

2022-08-22 08:01 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
これ一つのworkflowsに複数jobがあった場合は最後に上のようなjobを追加するだけでよろしいでしょうか？
https://github.com/Growthers/enshita/blob/main/.github/workflows/test.yml

2022-08-22 09:14 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +        if: steps.changes.outputs.client == 'true'
426c60d

2022-08-22 09:14 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +        if: steps.changes.outputs.client == 'true'
426c60d

2022-08-22 09:15 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +jobs:
9e07228

2022-08-22 09:15 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
9e07228

2022-08-22 09:15 UTC, re-taro commented on .github/workflows/client-fmt.yml
> +    runs-on: ubuntu-latest
426c60d

2022-08-22 10:17 UTC, Yusuke4869 approved these changes

2022-08-22 10:21 UTC, Sigumaa approved these changes

2022-08-22 14:17 UTC, mirror-kt approved these changes
(スマホからの適当レビューで私がミスってた部分があったのでそれだけ直しました)
LGTM

2022-08-22 14:23 UTC, Sigumaa approved these changes

2022-08-22 14:30 UTC, merged