feat(front): layout
Growthers/enshita pull request #123
Opened 2022-08-24 04:57 UTC by koutyuke

# issue
- #34 

# what
クソデカcommitの`layout`部分の`cherry-pick`です。

2022-08-24 19:44 UTC, Yusuke4869 requested changes

2022-08-24 19:44 UTC, Yusuke4869 commented on client/src/components/layout.tsx
> +  <div>
```diff
- <div>
+ <React.Fragment>
```

2022-08-25 02:36 UTC, koutyuke commented on client/src/components/layout.tsx
> +  <div>
[57688b1](https://github.com/Growthers/enshita/pull/123/commits/57688b16fb56a4776f56b149c34ceb8f7d16e855)

2022-08-25 02:46 UTC, Yusuke4869 approved these changes

2022-08-25 07:47 UTC, re-taro approved these changes

2022-08-25 08:13 UTC, merged