feat(front): Create Account Information and update Form
Growthers/enshita pull request #145
Opened 2022-08-26 17:26 UTC by koutyuke

# issue
- #92 

#what
アカウント情報表示ページと変更フォームの作成

2022-08-29 17:56 UTC, Yusuke4869 requested changes

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/routes.tsx
> +    <Route path="/account/info" component={AccountInfo} />
ここらへんを参考にネストできると思うので、`/account` でネストして下さい
https://github.com/molefrog/wouter#are-relative-routes-and-links-supported

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/components/form/accountInfoForm.tsx
> +  const [IsMatch, setMatch] = useState(false);
```suggestion
  const [isNotUpDate, setNotUpdate] = useState(false);
  const [isMatch, setMatch] = useState(false);
```

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/components/form/input/passwordArea.tsx
> +  const [IsShow, setShow] = useState(true);
```suggestion
  const [isShow, setShow] = useState(true);
```

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/components/form/zodSchema/model.ts
> +  .regex(/^[\w_]+?$/, {
`\w` は `[a-zA-Z0-9_]` です。
```suggestion
  .regex(/^\w+?$/, {
```

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/components/form/zodSchema/model.ts
> +  .regex(/^[\w_-]+?$/, {
```suggestion
  .regex(/^[\w-]+?$/, {
```

2022-08-29 17:56 UTC, Yusuke4869 commented on client/src/pages/account/accountInfo.tsx
> +  }
正直宗教なので、嫌だったら大丈夫です。
```ts
if (status === "loading") return <div>loading</div>;
```

2022-08-30 13:25 UTC, koutyuke commented on client/src/pages/account/accountInfo.tsx
> +  }
tokenの検証を削除したので修正はありません

2022-08-30 13:26 UTC, koutyuke commented on client/src/components/form/zodSchema/model.ts
> +  .regex(/^[\w_-]+?$/, {
[eb3467d](https://github.com/Growthers/enshita/pull/145/commits/eb3467dd3b637e252759b2c5355d3e0b332e317a)

2022-08-30 13:26 UTC, koutyuke commented on client/src/components/form/zodSchema/model.ts
> +  .regex(/^[\w_]+?$/, {
[eb3467d](https://github.com/Growthers/enshita/pull/145/commits/eb3467dd3b637e252759b2c5355d3e0b332e317a)

2022-08-30 13:27 UTC, koutyuke commented on client/src/components/form/input/passwordArea.tsx
> +  const [IsShow, setShow] = useState(true);
[095186d](https://github.com/Growthers/enshita/pull/145/commits/095186d04761819aea92a3ddee8f0b5da09a06c6)

2022-08-30 13:44 UTC, Yusuke4869 commented on client/src/routes.tsx
> +    <Route path="/account/info" component={AccountInfo} />
おそらくフォーマットがかかってないのでかけてください

2022-08-30 13:53 UTC, Yusuke4869 submitted a review, later dismissed
zod周りはよくわからないので、 @re-taro に投げます。
それ以外は大丈夫だと思います。

2022-09-01 19:31 UTC, Yusuke4869 requested changes
申し訳ないけどお願いします

2022-09-01 19:31 UTC, Yusuke4869 commented on client/src/components/form/accountInfoForm.tsx
> +          discription="mail Address"
```suggestion
          discription="Email Address"
```

2022-09-01 19:31 UTC, Yusuke4869 commented on client/src/components/form/accountInfoForm.tsx
> +          discription="current Password"
```suggestion
          discription="Current Password"
```

2022-09-02 04:19 UTC, koutyuke commented on client/src/components/form/accountInfoForm.tsx
> +          discription="current Password"
[9962d15](https://github.com/Growthers/enshita/pull/145/commits/9962d151d07d7eaef0c34b4ee50ffc697e9ee372)

2022-09-02 04:19 UTC, koutyuke commented on client/src/components/form/accountInfoForm.tsx
> +          discription="mail Address"
[9962d15](https://github.com/Growthers/enshita/pull/145/commits/9962d151d07d7eaef0c34b4ee50ffc697e9ee372)

2022-09-02 08:53 UTC, re-taro requested changes

2022-09-02 08:53 UTC, re-taro commented on client/src/components/form/accountInfoForm.tsx
> +
modelわけ、schemaわけを行ってください。

2022-09-02 12:14 UTC, koutyuke commented on client/src/components/form/accountInfoForm.tsx
> +
[aa8576e](https://github.com/Growthers/enshita/pull/145/commits/aa8576e44b37d8b2730f36f423a4d192c8d2cf21)
これで大丈夫でしょうか？

2022-09-04 13:55 UTC, Yusuke4869 approved these changes

2022-09-11 10:34 UTC, re-taro commented
merge after #292

2022-09-12 09:11 UTC, re-taro commented
#292 がマージされたのでそれに対応するように書き換えてください

2022-09-14 08:26 UTC, re-taro requested changes

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/icon-text-control.tsx
> +import { TextControlProps } from "~/components/account-info-form/type/model";
```suggestion
import type { TextControlProps } from "./type/model";
```

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/icon-text-control.tsx
> +import styles from "~/styles/components/form-modules/info-control/text.module.scss";
```suggestion
import styles from "~/styles/components/account-info-form/icon-text-control.module.scss";
```

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/icon-text-control.tsx
> +import styles from "~/styles/components/form-modules/info-control/text.module.scss";
命名を揃えてください

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/icon-text-control.tsx
> +import { TextControlProps } from "~/components/account-info-form/type/model";
typeインポートを用いてください

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/index.tsx
> +import { FC, useState } from "react";
```suggestion
import { useState } from "react";
import type { FC } from "react";
```

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/index.tsx
> +} from "~/components/account-info-form/type/model";
```suggestion
} from "./type/model";
```

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/index.tsx
> +        defaultValues={{
defaultvalueを動的な値にするのはアンチパターンです。ドキュメントを読んでください

2022-09-14 08:26 UTC, re-taro commented on client/src/components/account-info-form/index.tsx
> +      setMatch(true);
やりたいことはわかるんだけどmatchしてるかをtrueにするとmatchしてるとみなされます。命名をしっかりしてください。

2022-09-14 08:26 UTC, re-taro commented on client/src/components/form-element/type/model.ts
> +  icon: string;
型が違います

2022-09-14 08:26 UTC, re-taro commented on client/src/pages/account/info/index.tsx
> +    <AccountInfoForm mail="example@example.com" userName="hoge" />
おそらくAcountInfoFormコンポーネントの中身をここに書くべきです。

2022-09-14 08:26 UTC, re-taro commented on client/src/pages/account/info/index.tsx
> +import { FC } from "react";
```suggestion
import type { FC } from "react";
```

2022-09-14 08:26 UTC, re-taro commented on client/src/pages/account/info/index.tsx
> +    <AccountInfoForm mail="example@example.com" userName="hoge" />
そしたら
div
┗section
っていうdomにならない

2022-09-14 08:26 UTC, re-taro commented on client/src/stories/account-info-form/icon-text-control.stories.tsx
> +export const Default: Story = {};
インテグレーション的にinvalid validを検証してください

2022-09-14 08:26 UTC, re-taro commented on client/src/stories/account-info-form/password-control.stories.tsx
> +export const Default: Story = {};
インテグレーション的にinvalid validを検証してください

2022-09-14 08:26 UTC, re-taro commented on client/src/tests/components/account-info-form/icon-text-control.test.tsx
> +});
Storybookで検証したvalid invalidを用いてtestを書いてください

2022-09-14 08:26 UTC, re-taro commented on client/src/tests/components/account-info-form/password-control.test.tsx
> +});
Storybookで検証したvalid invalidを用いてtestを書いてください

2022-09-14 12:34 UTC, koutyuke commented on client/src/components/account-info-form/icon-text-control.tsx
> +import { TextControlProps } from "~/components/account-info-form/type/model";
[4023b0a](https://github.com/Growthers/enshita/pull/145/commits/4023b0a07821f1aba93d71ab74bbfa96677b965e)

2022-09-14 12:34 UTC, koutyuke commented on client/src/pages/account/info/index.tsx
> +import { FC } from "react";
[4023b0a](https://github.com/Growthers/enshita/pull/145/commits/4023b0a07821f1aba93d71ab74bbfa96677b965e)

2022-09-14 12:35 UTC, koutyuke commented on client/src/components/account-info-form/icon-text-control.tsx
> +import styles from "~/styles/components/form-modules/info-control/text.module.scss";
[7cd353d](https://github.com/Growthers/enshita/pull/145/commits/7cd353dabd7adacb69462dde0aa3fc162ef274f8)

2022-09-14 12:35 UTC, koutyuke commented on client/src/components/account-info-form/index.tsx
> +      setMatch(true);
[9112d52](https://github.com/Growthers/enshita/pull/145/commits/9112d52b712c70f6672c144de4ee06ee50024e1f)

2022-09-14 12:35 UTC, koutyuke commented on client/src/components/form-element/type/model.ts
> +  icon: string;
[b27bb5e](https://github.com/Growthers/enshita/pull/145/commits/b27bb5e8cec35f1ba4354a47f5bcc0fea1e822d0)

2022-09-14 12:37 UTC, koutyuke commented on client/src/pages/account/info/index.tsx
> +    <AccountInfoForm mail="example@example.com" userName="hoge" />
[c849e32](https://github.com/Growthers/enshita/pull/145/commits/c849e32a4c40d2799972314cd5e1f44b9d6b4ed6)
[2a60381](https://github.com/Growthers/enshita/pull/145/commits/2a60381a8467b96a4f1b46e06127a3572487082b)

2022-09-14 12:37 UTC, koutyuke commented on client/src/stories/account-info-form/password-control.stories.tsx
> +export const Default: Story = {};
[f230274](https://github.com/Growthers/enshita/pull/145/commits/f230274b560aa961cf4d3ba94c612627dbdc1dc7)

2022-09-14 12:37 UTC, koutyuke commented on client/src/stories/account-info-form/icon-text-control.stories.tsx
> +export const Default: Story = {};
[f230274](https://github.com/Growthers/enshita/pull/145/commits/f230274b560aa961cf4d3ba94c612627dbdc1dc7)

2022-09-14 12:37 UTC, koutyuke commented on client/src/stories/account-info-form/icon-text-control.stories.tsx
> +export const Default: Story = {};
[f230274](https://github.com/Growthers/enshita/pull/145/commits/f230274b560aa961cf4d3ba94c612627dbdc1dc7)

2022-09-14 12:37 UTC, koutyuke commented on client/src/tests/components/account-info-form/password-control.test.tsx
> +});
[14a33b2](https://github.com/Growthers/enshita/pull/145/commits/14a33b2d4a728ed7ca9632d4f9c6a46079d9b4cf)

2022-09-14 12:37 UTC, koutyuke commented on client/src/tests/components/account-info-form/icon-text-control.test.tsx
> +});
[14a33b2](https://github.com/Growthers/enshita/pull/145/commits/14a33b2d4a728ed7ca9632d4f9c6a46079d9b4cf)

2022-09-14 12:39 UTC, koutyuke commented on client/src/components/account-info-form/index.tsx
> +        defaultValues={{
[2a60381](https://github.com/Growthers/enshita/pull/145/commits/2a60381a8467b96a4f1b46e06127a3572487082b)
正直な話、token検証やlogin検証を実装していないので変更の余地ありです

2022-09-14 12:41 UTC, koutyuke commented
Login検証とtoken検証部分は @Yusuke4869 に言われた通りに場所だけ開けておきました(この開け方でいいのかは定かではありませんが)。
なので検証部分で多少なり修正があると思いますがよろしくお願いします。

2022-09-14 13:18 UTC, re-taro requested changes

2022-09-14 13:18 UTC, re-taro commented on client/src/components/form-element/type/model.ts
> +  icon: string;
あ、ごめんなさいそっちじゃなくてiconの型が違うって言いたかったです

2022-09-16 19:37 UTC, koutyuke commented on client/src/components/form-element/type/model.ts
> +  icon: string;
[872b9db](https://github.com/Growthers/enshita/pull/145/commits/872b9db89c42d57cea76431cac8a501df17427c1)

2024-11-01 09:49 UTC, closed without merging