Feat(front): add event page
Growthers/enshita pull request #196
Opened 2022-08-28 15:06 UTC by Yusuke4869

Refs: #26 

eventページの作成とそれに伴うコンポーネント、関数の実装

2022-08-29 08:38 UTC, re-taro requested changes

2022-08-29 08:38 UTC, re-taro commented on client/src/components/button/tweet-button.tsx
> +      icon="akar-icons:twitter-fill"
Twitterのアイコンは他のフォーマットもあるのでまぁ吟味してください。これでいいのならこれでいいけど

2022-08-29 08:38 UTC, re-taro commented on client/src/components/button/tweet-button.tsx
> +    // # を除去して , 区切りの文字列にする
ここの処理って受け渡されるpropsの実装見直したらいらないのでは...

2022-08-29 08:38 UTC, re-taro commented on client/src/components/button/anchor-button.tsx
> +    target={isSamePage ? "" : "_blank"}
やりたいことはわかるんだけど、これいる？

2022-08-29 08:38 UTC, re-taro commented on client/src/components/event/date.tsx
> +import styles from "~/styles/event/date.module.scss";
これeventはcomponents/にいるのでstylesの位置も変更してください

2022-08-29 08:38 UTC, re-taro commented on client/src/components/event/description.tsx
> +        .map((v, i) => (
もうちょいわかる変数名にしてください。

2022-08-29 08:38 UTC, re-taro commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
これは何を正規表現で弾いているんでしょうか

2022-08-29 08:38 UTC, re-taro commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/pages/event";
pageからcomponentsへ依存関係があるのはおかしいです

2022-08-29 08:38 UTC, re-taro commented on client/src/components/event/overview.tsx
> +EventOverview.defaultProps = {
defaultPropsは使わないでください

2022-08-29 08:38 UTC, re-taro commented on client/src/pages/event.tsx
> +  if (data === undefined) return <p>Loading...</p>;
Loadingはとりあえず手抜きって感じ？

2022-08-29 08:38 UTC, re-taro commented on client/src/routes.tsx
> +    <Route path="/event" component={Home} />
これだと/eventにいるのにUIHomeになるので/eventのときは/へリダイレクトするようにしましょう

2022-08-29 08:38 UTC, re-taro commented on client/src/stories/event/date.stories.tsx
> +
書き方をCSF3.0に統一してください

2022-08-29 08:38 UTC, re-taro commented on client/src/stories/event/description.stories.tsx
> +
書き方をCSF3.0に統一してください

2022-08-29 08:38 UTC, re-taro commented on client/src/stories/event/overview.stories.tsx
> +
書き方をCSF3.0に統一してください

2022-08-29 08:38 UTC, re-taro commented on client/src/styles/event/event.module.scss
> +@use "../variables" as var;
これ認識されます？

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/overview.test.tsx
> +
Storybookを使ってtestを書いてください

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/description.test.tsx
> +
Storybookを使ってtestを書いてください

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +import { describe, expect, test } from "vitest";
いらない

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/overview.test.tsx
> +import { describe, expect, test } from "vitest";
いらない

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/date.test.tsx
> +import { describe, expect, test } from "vitest";
いらない

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/description.test.tsx
> +import { describe, expect, test } from "vitest";
いらない

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/event/date.test.tsx
> +
Storybookを使ってtestを書いてください

2022-08-29 08:38 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
describeのフォーマットを統一してください

2022-08-29 08:38 UTC, re-taro commented on client/src/utils/date.ts
> +};
ここのレビューは諦めます。testをすべての関数でできるだけ多くの例で示してそれで動いていることを確認したら良しとします。

正常動作、異常動作、例外動作など。

2022-08-29 08:49 UTC, Yusuke4869 commented on client/src/components/button/anchor-button.tsx
> +    target={isSamePage ? "" : "_blank"}
変数名がよくない気がしてきた
samePageというより、sameOriginのときに使いたいっていう

2022-08-29 08:50 UTC, Yusuke4869 commented on client/src/pages/event.tsx
> +  if (data === undefined) return <p>Loading...</p>;
y

2022-08-29 08:50 UTC, Yusuke4869 commented on client/src/routes.tsx
> +    <Route path="/event" component={Home} />
了解です

2022-08-29 08:54 UTC, re-taro commented on client/src/components/button/anchor-button.tsx
> +    target={isSamePage ? "" : "_blank"}
あーそういうことか。それなら大丈夫です。

2022-08-29 08:54 UTC, re-taro commented on client/src/pages/event.tsx
> +  if (data === undefined) return <p>Loading...</p>;
ok

2022-08-29 08:54 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +    // # を除去して , 区切りの文字列にする
わざわざ配列に入れる必要はたしかにないかも
propsというより実装を見直します

2022-08-29 08:55 UTC, Yusuke4869 commented on client/src/components/event/date.tsx
> +import styles from "~/styles/event/date.module.scss";
はい、ごめんなさい

2022-08-29 08:55 UTC, Yusuke4869 commented on client/src/components/event/date.tsx
> +import styles from "~/styles/event/date.module.scss";
pageのスタイルはpage/にしますか？

2022-08-29 08:57 UTC, Yusuke4869 commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
弾いているというより、URLを抽出してaタグに置き換えるための処理

2022-08-29 08:57 UTC, Yusuke4869 commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
確かにわかりにくいのでコメント追加しておきます

2022-08-29 08:57 UTC, Yusuke4869 commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/pages/event";
別ファイルでtype管理します...

2022-08-29 10:27 UTC, re-taro commented on client/src/components/event/date.tsx
> +import styles from "~/styles/event/date.module.scss";
そうやね

2022-08-29 10:27 UTC, re-taro commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
なるほど理解です

2022-08-29 10:27 UTC, re-taro commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/pages/event";
はい

2022-08-29 18:27 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +      icon="akar-icons:twitter-fill"
これでとりあえずいきます

2022-08-30 16:42 UTC, Yusuke4869 commented on client/src/components/button/anchor-button.tsx
> +    target={isSamePage ? "" : "_blank"}
https://github.com/Growthers/enshita/pull/196/commits/316c5c8c21a4dc62dfada2d095e6affd79fef13d

2022-08-30 16:43 UTC, Yusuke4869 commented on client/src/tests/utils/date.test.tsx
> +import { describe, expect, test } from "vitest";
https://github.com/Growthers/enshita/pull/196/commits/ab9e53f8445e9aac71ea7cfc2e06969e956089ab

2022-08-30 16:43 UTC, Yusuke4869 commented on client/src/tests/event/overview.test.tsx
> +import { describe, expect, test } from "vitest";
https://github.com/Growthers/enshita/pull/196/commits/ab9e53f8445e9aac71ea7cfc2e06969e956089ab

2022-08-30 16:43 UTC, Yusuke4869 commented on client/src/tests/event/date.test.tsx
> +import { describe, expect, test } from "vitest";
https://github.com/Growthers/enshita/pull/196/commits/ab9e53f8445e9aac71ea7cfc2e06969e956089ab

2022-08-30 16:43 UTC, Yusuke4869 commented on client/src/tests/event/description.test.tsx
> +import { describe, expect, test } from "vitest";
https://github.com/Growthers/enshita/pull/196/commits/ab9e53f8445e9aac71ea7cfc2e06969e956089ab

2022-08-30 16:44 UTC, Yusuke4869 commented on client/src/utils/date.ts
> +};
関数は消しました
https://github.com/Growthers/enshita/pull/196/commits/9ecd86fad952a54cbf4fc6b95938a94073289580

2022-08-30 16:44 UTC, Yusuke4869 commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
どうでしょう
https://github.com/Growthers/enshita/pull/196/commits/1ab1143336b2b88bff9c5e76c38538150edaf35c

2022-08-30 16:45 UTC, Yusuke4869 commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
どうでしょう
https://github.com/Growthers/enshita/pull/196/commits/1ab1143336b2b88bff9c5e76c38538150edaf35c

2022-08-30 16:45 UTC, Yusuke4869 commented on client/src/components/event/description.tsx
> +        .map((v, i) => (
https://github.com/Growthers/enshita/pull/196/commits/1ab1143336b2b88bff9c5e76c38538150edaf35c

2022-08-30 16:46 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +      icon="akar-icons:twitter-fill"
https://github.com/Growthers/enshita/pull/196/commits/2abcb7a935dbbf9d6ee9e10a8becdc7c7073a175

2022-08-30 16:47 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +    // # を除去して , 区切りの文字列にする
https://github.com/Growthers/enshita/pull/196/commits/2abcb7a935dbbf9d6ee9e10a8becdc7c7073a175

2022-08-30 16:48 UTC, Yusuke4869 commented on client/src/routes.tsx
> +    <Route path="/event" component={Home} />
https://github.com/Growthers/enshita/pull/196/commits/2297f8344b6160c6ef447027aa87df4fa2611bb8

2022-08-30 17:02 UTC, Yusuke4869 commented on client/src/styles/event/event.module.scss
> +@use "../variables" as var;
黒を含め、開発者モードで色が適用されているのを確認してます

2022-08-30 17:03 UTC, Yusuke4869 commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
すべて関数名です

2022-08-30 17:04 UTC, re-taro commented on client/src/styles/event/event.module.scss
> +@use "../variables" as var;
なるほど、では好みの問題ですね末尾に.scssつけるのは。どちらで統一しましょう

2022-08-30 17:06 UTC, re-taro commented on client/src/components/event/description.tsx
> +  const urlPattern = /https?:\/\/[\w!?/+\-_~;.,*&@#$%=']+/gim;
LGT<

2022-08-30 17:06 UTC, Yusuke4869 commented on client/src/styles/event/event.module.scss
> +@use "../variables" as var;
なしでどうですか

2022-08-30 17:08 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
あー、いや他のtestとかは`(components) hogehoge`とかで統一されているので...

2022-08-30 17:10 UTC, Yusuke4869 commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
あー了解
`(function)` あたりにします

2022-08-30 17:17 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
あー、フォルダ名だとありがたい

2022-08-30 17:18 UTC, Yusuke4869 commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
フォルダ名？

2022-08-30 17:19 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
utilsとか

2022-08-30 17:20 UTC, re-taro commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
y

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/tests/utils/date.test.tsx
> +describe("fillzero", () => {
https://github.com/Growthers/enshita/pull/196/commits/3042f68154c54e1b4516e5259d25106ddbeba9a3

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/tests/event/date.test.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/c036ff881c7003468f9adf8c93a31705a50bc558

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/tests/event/description.test.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/c036ff881c7003468f9adf8c93a31705a50bc558

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/tests/event/overview.test.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/c036ff881c7003468f9adf8c93a31705a50bc558

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/stories/event/overview.stories.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/d77f66f6ee4e8410c6ccfd7d2bc00fece972f232

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/stories/event/description.stories.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/d77f66f6ee4e8410c6ccfd7d2bc00fece972f232

2022-08-30 18:50 UTC, Yusuke4869 commented on client/src/stories/event/date.stories.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/d77f66f6ee4e8410c6ccfd7d2bc00fece972f232

2022-08-30 18:51 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +TweetButton.defaultProps = {
他の引数の書き方とも関わってくるのでeslintのルールの判断をお願いします

2022-08-30 18:59 UTC, Yusuke4869 commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/pages/event";
https://github.com/Growthers/enshita/pull/196/commits/675ef770ab4231a61896985c355c9e97dcc1bb56

2022-09-01 06:51 UTC, re-taro commented on client/src/components/button/tweet-button.tsx
> +TweetButton.defaultProps = {
私は今の書き方で特にエラーが出ないのでわからない。どうすればいいんだ。
https://github.com/re-taro/enshita

2022-09-01 06:54 UTC, re-taro commented on client/src/utils/date.ts
> +};
utils/date.tsの他の関数はきちんと網羅されていますか？

2022-09-01 06:55 UTC, re-taro requested changes

2022-09-01 06:55 UTC, re-taro commented on client/src/tests/components/event/date.test.tsx
> +      <Default
defaultに値を入れるのではなくてそれぞれStoryを定義してそれを用いてください

2022-09-01 14:05 UTC, Yusuke4869 commented on client/src/utils/date.ts
> +};
y

2022-09-01 14:48 UTC, Yusuke4869 commented on client/src/tests/components/event/date.test.tsx
> +      <Default
https://github.com/Growthers/enshita/pull/196/commits/a4ab2541f7ac60d56135a27c489b74a7e9ca133d

2022-09-01 14:48 UTC, Yusuke4869 commented on client/src/components/button/tweet-button.tsx
> +TweetButton.defaultProps = {
https://github.com/Growthers/enshita/pull/196/commits/a4ab2541f7ac60d56135a27c489b74a7e9ca133d

2022-09-01 14:49 UTC, Yusuke4869 commented on client/src/components/event/overview.tsx
> +EventOverview.defaultProps = {
https://github.com/Growthers/enshita/pull/196/commits/a4ab2541f7ac60d56135a27c489b74a7e9ca133d

2022-09-01 14:49 UTC, Yusuke4869 commented on client/src/tests/components/event/date.test.tsx
> +      <Default
https://github.com/Growthers/enshita/pull/196/commits/3df1fd7208b22a86ce6bddf863a90f526dadfb80
https://github.com/Growthers/enshita/pull/196/commits/39d0776919b8606c5d6b3a6271d6a327402740b0

2022-09-01 14:49 UTC, Yusuke4869 commented on client/src/components/event/date.tsx
> +import styles from "~/styles/event/date.module.scss";
https://github.com/Growthers/enshita/pull/196/commits/39d0776919b8606c5d6b3a6271d6a327402740b0

2022-09-01 18:11 UTC, re-taro requested changes

2022-09-01 18:11 UTC, re-taro commented on client/src/tests/components/button/tweet-button.test.tsx
> +
snapshotだけじゃなくてroleのテストとかあってもいいのではないでしょうか

2022-09-01 18:11 UTC, re-taro commented on client/src/tests/components/event/overview.test.tsx
> +
buttonが押せるかなどをチェックしておいてもらえるとありがたい

2022-09-01 18:11 UTC, re-taro commented
Twitterのボタンについては確認しました。

2022-09-01 19:28 UTC, Yusuke4869 commented on client/src/tests/components/button/tweet-button.test.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/91887e7f245ee0a927db57f5032640022dd6e9a1

2022-09-01 19:28 UTC, Yusuke4869 commented on client/src/tests/components/event/overview.test.tsx
> +
https://github.com/Growthers/enshita/pull/196/commits/6cc291558ac9647842c856c163d53f6518306524

2022-09-02 04:11 UTC, re-taro requested changes

2022-09-02 04:11 UTC, re-taro commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/components/event/types/speaker-quota";
この型を割りとどこでも使うので共有用の型を作ってそこに入れてもらえると嬉しい

2022-09-02 04:55 UTC, Yusuke4869 commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/components/event/types/speaker-quota";
ok

2022-09-02 05:07 UTC, Yusuke4869 commented on client/src/components/event/overview.tsx
> +import type { SpeakerQuotaType } from "~/components/event/types/speaker-quota";
https://github.com/Growthers/enshita/pull/196/commits/69553c6492267f8b4cf5cb2e1a07cdb2d25522a1

2022-09-02 05:24 UTC, re-taro approved these changes

2022-09-02 11:37 UTC, koutyuke approved these changes

2022-09-02 11:37 UTC, merged