feat(back): add WebSocketResponse model
Growthers/enshita pull request #198
Opened 2022-08-28 15:27 UTC by YukiYuigishi

issue #179

2022-08-28 16:04 UTC, laminne reviewed
一応これらレスポンスだから\`json:"\<sting\>"\`書いてほしいです！

2022-08-28 16:07 UTC, Sigumaa commented on server/models/websocketresponse.go
> +	IconUrl  string
```suggestion
	IconURL  string
```

2022-08-29 22:59 UTC, Sigumaa requested changes

2022-08-29 22:59 UTC, Sigumaa commented on server/model/domain/websocketresponse.go
> +	Name     string `json:"Name"`
```suggestion
	Name     string `json:"name"`
```

2022-08-29 22:59 UTC, Sigumaa commented on server/model/domain/websocketresponse.go
> +	SceneType string `json:"screenType"`
なんでここ SceneType なのに `json:"screenType"`なんですか？

2022-08-30 03:05 UTC, YukiYuigishi commented on server/model/domain/websocketresponse.go
> +	SceneType string `json:"screenType"`
単純にTypoですね

2022-08-30 03:41 UTC, YukiYuigishi commented on server/model/domain/websocketresponse.go
> +	SceneType string `json:"screenType"`
https://github.com/Growthers/enshita/pull/198/commits/1856fa52be5aec1e2933741e503e25553d4c1ef9

2022-08-30 04:30 UTC, laminne requested changes

2022-08-30 04:30 UTC, laminne commented on server/model/domain/websocketresponse.go
> +	Payload T
```suggestion
	Payload T `json:"payload"`
```
ここにも要ると思う

2022-08-30 04:49 UTC, laminne approved these changes

2022-08-30 05:36 UTC, Sigumaa approved these changes

2022-08-30 05:37 UTC, merged