feat(front): Add front-end environment
Growthers/enshita pull request #2
Opened 2022-07-17 14:43 UTC by re-taro

GitHub Actions are only working on /front directory.

Refs: #1

2022-07-18 06:06 UTC, YukiYuigishi requested changes

2022-07-18 06:06 UTC, YukiYuigishi commented on .github/workflows/fmt.yml
> +      - dev
GitHub flowなのでdevは切りません

2022-07-18 06:06 UTC, YukiYuigishi commented on .github/workflows/lint.yml
> +      - dev
GitHub flowなのでdevは切りません

2022-07-18 06:06 UTC, YukiYuigishi commented on .github/workflows/test.yml
> +      - dev
GitHub flowなのでdevは切りません

2022-07-18 06:18 UTC, YukiYuigishi requested changes

2022-07-18 06:18 UTC, YukiYuigishi commented on front/LICENSE
> +                    GNU AFFERO GENERAL PUBLIC LICENSE
まだライセンスが確定してないので一旦消しといてください

2022-07-18 06:18 UTC, YukiYuigishi commented on front/package.json
> +  "license": "AGPL-3.0-only",
まだライセンスが確定してないので一旦消しといてください

2022-07-18 07:52 UTC, Sigumaa requested changes

2022-07-18 07:52 UTC, Sigumaa commented on .github/workflows/fmt.yml
> +      - dev
一応ここもです

2022-07-18 15:28 UTC, re-taro commented on .github/workflows/lint.yml
> +      - dev
a2eac3a

2022-07-18 15:28 UTC, re-taro commented on front/package.json
> +  "license": "AGPL-3.0-only",
8466e9b

2022-07-19 07:55 UTC, Sigumaa reviewed
renovate botについてなんだけど、automergeはfalseでもよくないかな、と思うんですがどうでしょうか。

2022-07-19 08:24 UTC, YukiYuigishi commented
> renovate botについてなんだけど、automergeはfalseでもよくないかな、と思うんですがどうでしょうか。
> 

個人的にはメジャーバージョンの更新でないので大丈夫だとは思います。
マイナーバージョンの更新なら、自動的に上げて問題が起きれば対処ってしたほうが保守的には楽だとは思います。

2022-07-19 08:24 UTC, YukiYuigishi approved these changes

2022-07-19 08:51 UTC, Yusuke4869 commented on .github/workflows/fmt.yml
> +          commit_message: 🤖 Auto-fixable format by github-actions
コミット規約に沿う形にしてほしいです

2022-07-19 09:28 UTC, re-taro commented on .github/workflows/fmt.yml
> +          commit_message: 🤖 Auto-fixable format by github-actions
i forgot it

2022-07-19 09:40 UTC, Yusuke4869 commented on front/src/index.html
> +    <title>Enshita</title>
```diff
- Enshita
+ enshita
```

2022-07-19 11:48 UTC, re-taro commented on .github/workflows/fmt.yml
> +          commit_message: 🤖 Auto-fixable format by github-actions
この場合type:は何になるんだろう。auto:かfix:

2022-07-19 11:56 UTC, Yusuke4869 commented on .github/workflows/fmt.yml
> +          commit_message: 🤖 Auto-fixable format by github-actions
個人的には `fix:` でいいと思います

2022-07-19 13:41 UTC, re-taro commented on front/src/index.html
> +    <title>Enshita</title>
d4a099a

2022-07-19 13:41 UTC, re-taro commented on .github/workflows/fmt.yml
> +          commit_message: 🤖 Auto-fixable format by github-actions
d4a099a

2022-07-19 13:42 UTC, YukiYuigishi approved these changes

2022-08-04 14:19 UTC, Yusuke4869 approved these changes

2022-08-08 14:45 UTC, sayoi341 approved these changes

2022-08-08 15:18 UTC, merged