feat(back): add GetPresentationOrderResponse domain
Growthers/enshita pull request #221
Opened 2022-08-28 17:31 UTC by dino3616

## Related Issues

- close #189 

## Reference Documents

- https://laminne.stoplight.io/docs/enshita/ac243c01e0427-

2022-08-28 23:39 UTC, Sigumaa requested changes

2022-08-28 23:39 UTC, Sigumaa commented on server/model/domain/get_presentation_order_response.go
> +	Duration time.Time `json:"duration"`
```suggestion


type GetPresentationOrderResponse []struct {
	ID       string    `json:"id"`
	Name     string    `json:"name"`
	Title    string    `json:"title"`
	Duration string `json:"duration"`
```

2022-08-29 01:32 UTC, Sigumaa requested changes

2022-08-29 01:32 UTC, Sigumaa commented on server/model/domain/get_presentation_order_response.go
> +type GetPresentationOrderResponse []struct {
```suggestion
type GetPresentationOrderResponse struct {
```

2022-08-29 01:33 UTC, Sigumaa requested changes

2022-08-29 01:33 UTC, Sigumaa commented on server/model/domain/get_presentation_order_response.go
> +import "time"
```suggestion

```

2022-08-29 01:33 UTC, Sigumaa commented on server/model/domain/get_presentation_order_response.go
> +	Duration time.Time `json:"duration"`
```suggestion
	Duration string `json:"duration"`
```

2022-08-29 07:58 UTC, Sigumaa submitted a review, later dismissed

2022-08-29 14:05 UTC, laminne submitted a review, later dismissed

2022-08-29 14:27 UTC, dino3616 commented on server/model/domain/get_presentation_order_response.go
> +	Duration string `json:"duration"`
揃えたい(なんで揃ってないんだ...(困惑)

2022-08-29 14:38 UTC, Sigumaa approved these changes

2022-08-29 14:41 UTC, laminne approved these changes

2022-08-29 14:44 UTC, merged