Feat(front): レイアウト回りの修正
Growthers/enshita pull request #228
Opened 2022-08-29 10:48 UTC by koutyuke

# issue
- #146 

# what
footer header laytou のデザイン崩れの修正およびボタンの追加

2022-08-29 13:40 UTC, Yusuke4869 submitted a review, later dismissed

2022-08-30 13:54 UTC, Yusuke4869 submitted a review, later dismissed

2022-08-30 18:02 UTC, sayoi341 submitted a review, later dismissed

2022-08-30 18:03 UTC, re-taro requested changes

2022-08-30 18:03 UTC, re-taro commented on client/src/app.tsx
> +    <CookiesProvider>
layoutの修正なのにcockieに関する変更があります

2022-08-30 18:03 UTC, re-taro commented on client/package.json
> +    "react-cookie": "^4.1.1",
layoutの修正なのにcockieに関する変更があります

2022-08-30 21:55 UTC, koutyuke commented on client/package.json
> +    "react-cookie": "^4.1.1",
[827f93a](https://github.com/Growthers/enshita/pull/228/commits/827f93a16b149801934f19b617e4768bf7d955ce)

2022-08-30 21:55 UTC, koutyuke commented on client/src/app.tsx
> +    <CookiesProvider>
[827f93a](https://github.com/Growthers/enshita/pull/228/commits/827f93a16b149801934f19b617e4768bf7d955ce)
変更を削除しました

2022-09-01 06:44 UTC, re-taro commented
Storybookで挙動を確認したいので最新のmainをmergeしてください

2022-09-01 06:45 UTC, re-taro requested changes
Storybookで挙動を確認したいので最新のmainをmergeしてください

2022-09-01 06:53 UTC, koutyuke commented
mergeしました。確認をお願いします

2022-09-01 16:25 UTC, Yusuke4869 approved these changes

2022-09-02 05:05 UTC, re-taro approved these changes

2022-09-02 05:06 UTC, merged