feat: add CreateFormRequest entity
Growthers/enshita pull request #242
Opened 2022-08-29 18:33 UTC by dino3616

## Related Issues

- close #213 

## Reference Documents

- https://laminne.stoplight.io/docs/enshita/c7961250c3693-

2022-08-29 23:24 UTC, Sigumaa requested changes

2022-08-29 23:24 UTC, Sigumaa commented on server/model/domain/create_form_request.go
> +			Time         time.Time `json:"time"`
```suggestion
			Time         int `json:"time"`
```

2022-08-30 08:14 UTC, Sigumaa approved these changes

2022-08-30 08:18 UTC, laminne approved these changes

2022-08-30 08:24 UTC, merged