feat: add UpdateFormInfoRequest entity
Growthers/enshita pull request #243
Opened 2022-08-29 18:55 UTC by dino3616

## Related Issues

- close #214 

## Reference Documents

- https://laminne.stoplight.io/docs/enshita/a9b87ddea0b16-

2022-08-29 23:26 UTC, Sigumaa requested changes

2022-08-29 23:26 UTC, Sigumaa commented on server/model/domain/update_form_info_request.go
> +			Time         time.Time `json:"time"`
```suggestion
			Time         int `json:"time"`
```

2022-08-30 08:15 UTC, Sigumaa approved these changes

2022-08-30 08:17 UTC, laminne approved these changes

2022-08-30 08:20 UTC, merged