feat: add ConfigDeliveryLayoutRequest entity
Growthers/enshita pull request #245
Opened 2022-08-29 19:16 UTC by dino3616

## Related Issues

- close #217 

## Reference Documents

- https://laminne.stoplight.io/docs/enshita/641644d5c04db-

2022-08-29 23:27 UTC, Sigumaa approved these changes

2022-08-30 01:06 UTC, laminne requested changes

2022-08-30 01:06 UTC, laminne commented on server/model/domain/config_delivery_layout_request.go
> +type ConfigDeliveryLayoutRequest struct {
`Delivery` って命名おかしくないですか...?
`Streaming` のほうがわかりやすい気がします

2022-08-30 06:28 UTC, Sigumaa commented on server/model/domain/config_delivery_layout_request.go
> +type ConfigDeliveryLayoutRequest struct {
私だったら`SetLayoutConfig`とかにするかなあ

2022-08-30 07:58 UTC, dino3616 commented on server/model/domain/config_delivery_layout_request.go
> +type ConfigDeliveryLayoutRequest struct {
Streaming入れると長いので`SetLayoutConfig`にしますか

2022-08-30 08:06 UTC, Sigumaa approved these changes

2022-08-30 08:14 UTC, merged