feat(front): create status message component
Growthers/enshita pull request #261
Opened 2022-08-30 15:28 UTC by koutyuke

# issue
- #135 

# what

ステータスメッセージを表示するコンポーネントの作成

2022-09-02 09:27 UTC, re-taro requested changes

2022-09-02 09:27 UTC, re-taro commented on client/src/components/layout/statusMessage.tsx
> +type StatusMessgeProps = {
typeは分けてください。

2022-09-02 09:27 UTC, re-taro commented on client/src/components/layout/statusMessage.tsx
> +  message: string;
status codeとmessage以外に
```ts
<p>
  Oh... This URL is wrong.
  <br />
  please check again page URL.
</p>
```
って部分も可変であるべきです

2022-09-02 09:27 UTC, re-taro commented on client/src/components/layout/statusMessage.tsx
> +import { FC } from "react";
type importを用いてください

2022-09-02 11:54 UTC, koutyuke commented on client/src/components/layout/statusMessage.tsx
> +import { FC } from "react";
[d2b132d](https://github.com/Growthers/enshita/pull/261/commits/d2b132d0bd8b19f14070a86a8aae244b04c5cc64)

2022-09-02 11:57 UTC, koutyuke commented on client/src/components/layout/statusMessage.tsx
> +  message: string;
[360b113](https://github.com/Growthers/enshita/pull/261/commits/360b113c3e6c45542a06e61a1fd4ff7084c687b3)
可変にしましたが`children`でまとめちゃったので変更があればRCを出してください

2022-09-05 12:20 UTC, re-taro commented on client/src/components/layout/statusMessage.tsx
> +  message: string;
いいと思います！

2022-09-05 12:26 UTC, Yusuke4869 approved these changes

2022-09-05 13:29 UTC, re-taro approved these changes

2022-09-09 08:28 UTC, merged