feat: UserRepositoryとその周辺の仮実装
Growthers/enshita pull request #262
Opened 2022-08-30 15:47 UTC by laminne

※とりあえずです
※Draftでも容赦なくRC飛ばしてください

2022-08-30 17:19 UTC, mirror-kt requested changes

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
domain objectを受け取ってdomain objectを返してください。
entity.Userはリポジトリの内部でのみ使用し、引数や戻り値として使用してはいけません。
entity.*は「データベース上のデータをGoから扱えるようにしたもの」以上の何でもないので、「ドメイン知識としてのUserを表すstruct」は別にあるべきです。
こうすることで例えば「データベースをNoSQLに変えたい、NoSQLのデータのGo表現はgormのものと違う」なんてときに影響する範囲を絞ることができます(Repositoryインターフェイスを満たす新たなstructを定義すれば、そこにはgormに依存したコードは現れない)

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +	if len(password) >= 4 {
パスワードが4文字未満だった場合パスワードが空のrowが挿入されそう

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
あと引数が多いのでCreateUserOptionみたいなstructを作ってそれを渡すべきかもしれません。
roleが生intを渡しているのも気になるので、DefinedTypeとかを使ってちゃんと型をつけた方が良さそう。

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +		hashed := argon2.IDKey([]byte(password), []byte(salt), 1, 6710, 2, 32)
別関数に切っておくべき

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
戻り値はポインタ型の方がいいかもしれない
empty Userを返しているところはnilを返しましょう

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +		salt := "AndjefkjDSn3Nd+w$siv"
saltはパスワードごとにランダムに生成しないと意味がありません…

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/gorm/user.go
> +		salt := "AndjefkjDSn3Nd+w$siv"
データベースに保存する際にsaltとhash化済みパスワードをペアで保存してください

2022-08-30 17:19 UTC, mirror-kt commented on server/repository/repository.go
> +	UserRepository
埋め込み、うーーんという感じ
埋め込むよりも、複数Repositoryの操作が必要ならそれをまとめたServiceを定義すべきな気がします

2022-08-30 17:25 UTC, mirror-kt commented
あとgodocちゃんと書いてください

2022-09-03 15:37 UTC, mirror-kt requested changes

2022-09-03 15:37 UTC, mirror-kt commented on server/util/password_encoder.go
> +		return ""
エラーを握りつぶさないでください

2022-09-03 15:37 UTC, mirror-kt commented on server/util/password_encoder.go
> +	return EncodedPassword(argon2.IDKey([]byte(rawPassword), []byte(salt), 0, 20, 20, 20))
randomは[]byteなのにそれをstringにしてまた[]byteにしています。

2022-09-03 15:37 UTC, mirror-kt commented on server/util/password_encoder.go
> +	return EncodedPassword(argon2.IDKey([]byte(rawPassword), []byte(salt), 0, 20, 20, 20))
DecodeではBase64処理していますが、Encode側ちゃんとこうなっていますか？
```
/*
	ハッシュされたパスワードの仕様
	<ハッシュ済みパスワード(Base64)>.<ソルト(ランダム文字列)>
	↑全体をもう一度Base64エンコードする
*/
```

2022-09-03 15:45 UTC, mirror-kt commented on server/util/password_encoder.go
> +	return EncodedPassword(argon2.IDKey([]byte(rawPassword), []byte(salt), 0, 20, 20, 20))
こういうミスをさせないために、
```golang
type EncodedPassword struct {
    hashedPassword string
    salt string
}

func (p *EncodedPassword) String() string {
    // <ハッシュ済みパスワード(Base64)>.<ソルト(ランダム文字列)>
    // 全体をもう一度base64エンコード
}

func NewEncodedPassword(hashedPassword, salt string): *EncodedPassword {
    return &EncodedPassword { 
        hashedPassword: hashedPassword, 
        salt: salt
    }
}
```
とかするのはありかも

2022-09-05 14:36 UTC, laminne commented
作業リスト
1. server/repository/gorm/user.go
L12: CreateUserを、CreateOperator/CreateAdminに分割
2. server/repository/gorm/user.go
L21-23: パスワードの文字数を消して、 server/util/password_encoder.go L28 EncodePasswordに動かす
3. Create<Operator/Admin>はdomain.<name>を受け取って*domain.<name>を返すようにする
4. 多分 server/repository/repository.go の記述は必要なさそう

2022-09-06 19:47 UTC, mirror-kt requested changes

2022-09-06 19:47 UTC, mirror-kt commented on server/repository/gorm/user.go
> +	encoder := util.NewArgon2PasswordEncoder()
DIしてください

2022-09-06 19:47 UTC, mirror-kt commented on server/util/password_encoder.go
> +	<ハッシュ済みパスワード(Base64)>.<ソルト(ランダム文字列)>
ところでこれこんなに複雑なことする必要あります？
`<hash algorithm>:<hash as hex string>:<salt as hex string>`
(Base64なし)
とかでいい気がする

2022-09-06 19:47 UTC, mirror-kt commented on server/util/password_encoder.go
> +	<ハッシュ済みパスワード(Base64)>.<ソルト(ランダム文字列)>
hash algorithmは今後万が一ハッシュアルゴリズムを変える場合にマイグレーションに必要。
要るときになったら足すのでもいいっちゃいいけど

2022-09-12 11:56 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +	encoder := util.NewArgon2PasswordEncoder()
6d187b8ea1f95eae2f898b2f67fd2847d82ca15c

2022-09-12 12:13 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
おそらく修正済みなので確認お願いします。
@mirror-kt

2022-09-12 12:13 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
おそらく修正済みなので確認お願いします。
@mirror-kt

2022-09-12 12:13 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
おそらく修正済みなので確認お願いします。
@mirror-kt

2022-09-12 12:24 UTC, mirror-kt commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
>domain objectを受け取ってdomain objectを返してください。
entity.Userはリポジトリの内部でのみ使用し、引数や戻り値として使用してはいけません。
entity.*は「データベース上のデータをGoから扱えるようにしたもの」以上の何でもないので、「ドメイン知識としてのUserを表すstruct」は別にあるべきです。
こうすることで例えば「データベースをNoSQLに変えたい、NoSQLのデータのGo表現はgormのものと違う」なんてときに影響する範囲を絞ることができます(Repositoryインターフェイスを満たす新たなstructを定義すれば、そこにはgormに依存したコードは現れない)

> 戻り値はポインタ型の方がいいかもしれない
empty Userを返しているところはnilを返しましょう

こっちはOK

> あと引数が多いのでCreateUserOptionみたいなstructを作ってそれを渡すべきかもしれません。
roleが生intを渡しているのも気になるので、DefinedTypeとかを使ってちゃんと型をつけた方が良さそう。

こっちは多分まだ

2022-09-12 12:35 UTC, mirror-kt commented on server/repository/gorm/user.go
> +	if len(password) >= 4 {
今Argon2PasswordEncoder2で弾いていないけどこれはアルゴリズム上の不具合を生みそう。

2022-09-12 12:37 UTC, mirror-kt commented on server/model/domain/user.go
> +type UserRole int
AdminとMember、定数値として宣言しておくべきな気がする

2022-09-12 12:37 UTC, mirror-kt commented on server/repository/errors.go
> +var (
```suggestion
const (
```

2022-09-12 16:23 UTC, YukiYuigishi commented on server/model/domain/user.go
> +type UserRole int
1cfb24d75c1ddf0dfbacea7e6aee11406576450c

2022-09-13 17:18 UTC, YukiYuigishi commented on server/util/password_encoder.go
> +	<ハッシュ済みパスワード(Base64)>.<ソルト(ランダム文字列)>
b825c023fa5474b33dca010dac41bfaf94b82118

2022-09-14 13:12 UTC, laminne commented on server/repository/errors.go
> +const (
ここ、constantじゃないからvarにしないと落ちる(私のガバ
```suggestion
var (
```

2022-09-14 13:25 UTC, dino3616 commented on server/model/domain/user.go
> +// userRole ユーザーのロール
細かいですが、ここ多分`UserRole`ですよね？

2022-09-14 13:25 UTC, dino3616 commented on server/repository/errors.go
> +	ArgIDNilErr = errors.New("id is nil")
自分の環境ではこんなエラーが吐かれてますが、そちらでは大丈夫ですか？
![image](https://user-images.githubusercontent.com/85730998/190166140-452ffc40-42b0-4ce3-9782-a691d9cff6ac.png)

2022-09-14 13:26 UTC, dino3616 commented on server/model/domain/user.go
> +// userRole ユーザーのロール
多分これ？

> ここ、constantじゃないからvarにしないと落ちる(私のガバ
https://github.com/Growthers/enshita/pull/262#discussion_r970788858

2022-09-14 13:27 UTC, dino3616 commented on server/repository/errors.go
> +	ArgIDNilErr = errors.New("id is nil")
多分これ？

> ここ、constantじゃないからvarにしないと落ちる(私のガバ
https://github.com/Growthers/enshita/pull/262#discussion_r970788858

2022-09-14 14:18 UTC, YukiYuigishi commented on server/repository/errors.go
> +	ArgIDNilErr = errors.New("id is nil")
1d317f9da7247165ac6229feecb8c0cf2a79c03e

2022-09-15 03:37 UTC, dino3616 approved these changes

2022-09-15 04:15 UTC, dino3616 requested changes

2022-09-15 04:15 UTC, dino3616 commented on server/repository/gorm/user.go
> +	user := &domain.User{
gormに渡す`user`は`&entity.User`じゃないといけないようです。
ref: https://discord.com/channels/815946801755586570/1007261045796118608/1019816107231678464

2022-09-15 04:15 UTC, dino3616 commented on server/repository/gorm/user.go
> +	user := &domain.User{
なのでこっちも`&entity.User`に変更する必要がありますね。

2022-09-15 06:34 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +	user := &domain.User{
daf6026

2022-09-15 06:52 UTC, laminne commented on server/util/password_encoder.go
> +/*
仕様違うからここ消したら？

2022-09-15 07:17 UTC, YukiYuigishi commented on server/util/password_encoder.go
> +/*
582e48f

2022-09-15 10:06 UTC, YukiYuigishi commented on server/repository/repository.go
> +	UserRepository
削除したため解決

2022-09-15 10:07 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +	user := &domain.User{
daf60260406581ce8004713734da575f606157f5

2022-09-15 10:20 UTC, YukiYuigishi commented on server/repository/gorm/user.go
> +func (repo *Repository) CreateUser(userID, email, userName, password string, role int) (entity.User, error) {
一応解決したのでresolve

2022-09-15 10:22 UTC, Sigumaa approved these changes

2022-09-15 11:15 UTC, dino3616 approved these changes

2022-09-15 11:49 UTC, YukiYuigishi submitted a review, later dismissed

2022-09-15 14:26 UTC, mirror-kt requested changes

2022-09-15 14:26 UTC, mirror-kt commented on server/model/domain/user.go
> +	Password string   `json:"password"`
`json: "password"`、ヤバくないですか…？

2022-09-15 14:26 UTC, mirror-kt commented on server/util/password_encoder.go
> +	hashedPassword := argon2.IDKey([]byte(rawPassword), []byte(salt), 2, 20, 20, 20)
argon2.IDKeyを呼ぶのを関数切ってください。
IsMatchPasswordとEncodePasswordで同じ条件でIDKeyを呼ばなければいけないはずですが、同じコードが複数箇所に書かれているのはDRYでありません。

2022-09-15 14:43 UTC, YukiYuigishi commented on server/model/domain/user.go
> +	Password string   `json:"password"`
348d90a

2022-09-15 15:07 UTC, mirror-kt commented on server/util/password_encoder.go
> +}
`util/passwordencoder/argon2/argon2.go` とかに切りましょう.
ついでにこのファイル自体も`util/passwordencoder/passwordencoder.go` とかにすると嬉しい.

2022-09-15 15:14 UTC, mirror-kt commented on server/util/password_encoder.go
> +}
```
util/
    L passwordencoder/
        L passwordencoder.go
        L argon2.go
```
のほうがいいかも
`const HashAlgorithm` は argon2.go内で `const hashAlgorithm` として宣言してください(外部からアクセスされたくない)

2022-09-15 16:17 UTC, YukiYuigishi commented on server/util/password_encoder.go
> +}
https://github.com/Growthers/enshita/pull/262/commits/14f8fd050cda6c906815e0a344750422eba5d95a

2022-09-15 16:36 UTC, Sigumaa submitted a review, later dismissed

2022-09-16 04:34 UTC, mirror-kt requested changes

2022-09-16 04:34 UTC, mirror-kt commented on server/password/encorder.go
> +}
これも全部argon2.goに移動してください。
encoder.goにはEncoderとEncodedPassword以外のものを置いてはいけません。

2022-09-16 04:34 UTC, mirror-kt commented on server/password/argon2.go
> +const hashAlgorithm = "Argon2"
そういえばこれ同一パッケージだからencoder.goから見えるのか…
やっぱり`password/argon2/`パッケージ切ったほうがいいかも…？

2022-09-16 04:34 UTC, mirror-kt commented on server/password/encorder_test.go
> +func TestIsMatchPassword(t *testing.T) {
これはEncoderのテストではなくArgon2PasswordEncoderのテストです。
(interfaceは「できること」の定義でしか無いので、実際の挙動を持っていない=テストできるはずがない)

2022-09-16 04:34 UTC, mirror-kt commented on server/password/encorder_test.go
> +func TestIsMatchPassword(t *testing.T) {
`password/argon2/argon2_test.go` とかに移動してください

2022-09-16 06:51 UTC, YukiYuigishi commented on server/password/encorder_test.go
> +func TestIsMatchPassword(t *testing.T) {
e57097443ff3ace6cedc29bd7aaef5caa9318eba

2022-09-16 06:52 UTC, YukiYuigishi commented on server/password/encorder.go
> +}
e57097443ff3ace6cedc29bd7aaef5caa9318eba

2022-09-16 07:05 UTC, mirror-kt approved these changes

2022-09-16 08:18 UTC, Sigumaa approved these changes

2022-09-16 08:19 UTC, merged