fix(front): Fixed a bug that prevented Vite's HMR from working.
Growthers/enshita pull request #37
Opened 2022-08-14 14:30 UTC by re-taro

The script element is not a void element.

Refs: #36

2022-08-14 14:47 UTC, Yusuke4869 approved these changes

2022-08-14 15:01 UTC, Yusuke4869 requested changes

2022-08-14 15:01 UTC, Yusuke4869 commented on .github/workflows/test.yml
> +    default:
```
The workflow is not valid. .github/workflows/test.yml (Line: 16, Col: 5): Unexpected value 'default'
```
とのことです

2022-08-14 15:01 UTC, Yusuke4869 commented on .github/workflows/fmt.yml
> +    default:
```
The workflow is not valid. .github/workflows/fmt.yml (Line: 16, Col: 5): Unexpected value 'default'
```
とのことです

2022-08-14 15:01 UTC, Yusuke4869 commented on .github/workflows/lint.yml
> +    default:
```
The workflow is not valid. .github/workflows/lint.yml (Line: 16, Col: 5): Unexpected value 'default'
```
とのことです

2022-08-14 15:05 UTC, re-taro commented on .github/workflows/lint.yml
> +    default:
321b2cd

2022-08-14 15:05 UTC, re-taro commented on .github/workflows/fmt.yml
> +    default:
321b2cd

2022-08-14 15:05 UTC, re-taro commented on .github/workflows/test.yml
> +    default:
321b2cd

2022-08-14 15:06 UTC, re-taro commented
yarnのcacheがいないと言われているので少々お待ち下さい

2022-08-14 15:37 UTC, Yusuke4869 submitted a review, later dismissed

2022-08-15 01:59 UTC, koutyuke submitted a review, later dismissed

2022-08-15 03:26 UTC, Yusuke4869 approved these changes

2022-08-15 07:38 UTC, koutyuke approved these changes

2022-08-15 08:23 UTC, sayoi341 approved these changes

2022-08-15 08:44 UTC, merged