feat(front): feat footer&header&layout
Growthers/enshita pull request #49
Opened 2022-08-15 20:55 UTC by koutyuke

2022-08-16 02:55 UTC, re-taro requested changes

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="./" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-homepage"]}`}>Home Page</a>
```suggestion
            <a href={"https://growthers.dev/"} className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-homepage"]}`} target={"_blank"} rel={"noopener noreferrer"}>Home Page</a>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="twitter" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`}>Twitter</a>
```suggestion
            <a href={"https://twitter.com/UdcGrowthers/"} className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`} target={"_blank"} rel={"noopener noreferrer"}>Twitter</a>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="github" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-github"]}`}>GitHub</a>
```suggestion
            <a href={"https://github.com/Growthers/"} className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-github"]}`} target={"_blank"} rel={"noopener noreferrer"}>GitHub</a>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +      <div className={styles["enshita-footer-copyright"]}>
```suggestion
      <p className={styles["enshita-footer-copyright"]}><small>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +      </div>
```suggestion
      </small></p>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +          <div className={`${styles["enshita-footer-logo"]} ${styles["enshita-footer-hidden"]}`}>
div以外のtagを用いてください。pとかheadingとか

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +            <div className={styles["enshita-footer-about"]}>About Growthers</div>
```suggestion
            <p className={styles["enshita-footer-about"]}>About Growthers</p>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/footer.tsx
> +            <div className={styles["enshita-footer-about"]}>About Growthers</div>
リストになっているので無理にgridで合わせるんじゃなくて箇条書きの部分はlistにしたほうが良いでしょう

```suggestion
            <div className={styles["enshita-footer-about"]}>About Growthers</div>
            <ul>
              <li>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/header.tsx
> +    <div className={styles["enshita-header-logo"]}>
div以外のtagを用いてください。pとかheadingとか

2022-08-16 02:55 UTC, re-taro commented on front/src/components/header.tsx
> +  <header className={`${styles["enshita-header"]} ${styles["enshita-header-pc"]}`}>
```suggestion
  <header className={`${styles["enshita-header"]} ${styles["enshita-header-pc"]}`} role={"banner"}>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/layout.tsx
> +    <div className={style["enshita-layout-body"]}>
```suggestion
    <main className={style["enshita-layout-body"]}>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/components/layout.tsx
> +    </div>
```suggestion
    </main>
```

2022-08-16 02:55 UTC, re-taro commented on front/src/app.tsx
>  import React from "react";
全ページでLayoutは共通なのでこっちにLayoutを読み込む処理を書くべきです

2022-08-16 02:55 UTC, re-taro commented on front/src/app.tsx
> +import "~/styles/global.scss"
.storybook/preview.js内でもglobal.scssを読み込ませてください

2022-08-16 02:55 UTC, re-taro commented on front/src/app.tsx
> +import "~/styles/global.scss"
global.scssでリセットまがいなことしていますが、普通にリセットCSSを読み込みましょう。

2022-08-16 02:55 UTC, re-taro commented on front/src/styles/global.scss
> +  font-family: "Inter","NotoSansJp"
fallback fontを設定してください。

2022-08-16 02:55 UTC, re-taro commented on front/src/styles/global.scss
> +       url("../../public/fonts/Inter.eot") format("embedded-opentype");
```suggestion
       url("../../public/fonts/Inter.eot") format("embedded-opentype");
  font-style: normal;
  font-weight: 400;
  font-display: fallback;
```

2022-08-16 02:55 UTC, re-taro commented on front/src/styles/global.scss
> +       url("../../public/fonts/NotoSansJp.eot") format("embedded-opentype");
```suggestion
       url("../../public/fonts/NotoSansJp.eot") format("embedded-opentype");
  font-style: normal;
  font-weight: 400;
  font-display: fallback;
```

2022-08-16 02:59 UTC, re-taro commented
あと、きちんとtestとstorybookへの登録をお願いします。testはsnap shotテストとロールを確認するテストがあったら良しとします。

2022-08-16 13:45 UTC, Yusuke4869 requested changes

2022-08-16 13:45 UTC, Yusuke4869 commented on front/src/components/layout.tsx
> +  <div>
```diff
- <div>
+ <>
```

2022-08-16 13:45 UTC, Yusuke4869 commented on front/src/components/layout.tsx
> +  </div>
```diff
- </div>
+ </>

2022-08-16 13:45 UTC, Yusuke4869 commented on front/src/styles/footer.module.scss
> +  height: calc(20vh - 20px);
20pxの意図をコメントアウトなどで書いてほしいです

2022-08-16 13:49 UTC, re-taro commented on front/src/components/layout.tsx
> +  <div>
Fragmentを省略するの嫌いなんだけど、どうですか

2022-08-16 13:51 UTC, Yusuke4869 commented on front/src/components/layout.tsx
> +  <div>
個人的にはheader, main, footerをdivで囲むほうが好ましくないと思うのですが、いかがでしょう

2022-08-16 13:52 UTC, re-taro commented on front/src/components/layout.tsx
> +  <div>
違います。`<>`こうやって書くより`<Fragment>`って書かないかってことです

2022-08-16 13:53 UTC, Yusuke4869 commented on front/src/components/layout.tsx
> +  <div>
それは入れますか

2022-08-16 13:55 UTC, re-taro commented on front/src/components/layout.tsx
> +  <div>
入れましょう。

2022-08-16 14:13 UTC, koutyuke commented on front/src/styles/footer.module.scss
> +  height: calc(20vh - 20px);
paddingにより大きさが変わってしまったことへの調整として入れました。
しかし、box-sizing: border-box を入れるため calc(* -20px) は削除します。

2022-08-16 14:23 UTC, koutyuke commented on front/src/styles/footer.module.scss
> +  height: calc(20vh - 20px);
aa15c07

2022-08-16 14:23 UTC, koutyuke commented on front/src/components/layout.tsx
> +  </div>
aa15c07

2022-08-16 14:23 UTC, koutyuke commented on front/src/components/layout.tsx
> +  <div>
aa15c07

2022-08-16 14:33 UTC, koutyuke commented on front/src/styles/global.scss
> +       url("../../public/fonts/Inter.eot") format("embedded-opentype");
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:33 UTC, koutyuke commented on front/src/styles/global.scss
> +  font-family: "Inter","NotoSansJp"
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:35 UTC, koutyuke commented on front/src/app.tsx
> +import "~/styles/global.scss"
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
リセットCSSとして `normalize.css` を入れました。

2022-08-16 14:36 UTC, koutyuke commented on front/src/app.tsx
> +import "~/styles/global.scss"
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
読み込ませました。

2022-08-16 14:40 UTC, koutyuke commented on front/src/app.tsx
>  import React from "react";
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
`app.tsx`で読み込ませました。

2022-08-16 14:41 UTC, koutyuke commented on front/src/components/layout.tsx
> +    </div>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
変更しました。

2022-08-16 14:41 UTC, koutyuke commented on front/src/components/layout.tsx
> +    <div className={style["enshita-layout-body"]}>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:42 UTC, koutyuke commented on front/src/components/header.tsx
> +  <header className={`${styles["enshita-header"]} ${styles["enshita-header-pc"]}`}>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
`{"hoge"}`を使ったらエラーを吐いたので`"hoge"`にて変更しました。

2022-08-16 14:42 UTC, koutyuke commented on front/src/components/header.tsx
> +    <div className={styles["enshita-header-logo"]}>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:44 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <div className={styles["enshita-footer-about"]}>About Growthers</div>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
`ul` `li` tagを用いました。それに伴いgridをやめて最小限の`flex`のみで対応しました

2022-08-16 14:44 UTC, koutyuke commented on front/src/components/footer.tsx
> +      <div className={styles["enshita-footer-copyright"]}>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:44 UTC, koutyuke commented on front/src/components/footer.tsx
> +      </div>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)

2022-08-16 14:45 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="github" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-github"]}`}>GitHub</a>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
{"hoge"}を使ったらエラーを吐いたので"hoge"にて変更しました。

2022-08-16 14:45 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="./" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-homepage"]}`}>Home Page</a>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
{"hoge"}を使ったらエラーを吐いたので"hoge"にて変更しました。

2022-08-16 14:45 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="twitter" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`}>Twitter</a>
[036a01e](https://github.com/Growthers/enshita/pull/49/commits/036a01e366f158cfd3d9d53515c60988e7e44f25)
{"hoge"}を使ったらエラーを吐いたので"hoge"にて変更しました。

2022-08-16 15:05 UTC, YukiYuigishi commented
> _ No description provided. _
@koutyuke 
Descriptionを書いてください。最低限issueへのリンクは載せてください

2022-08-16 15:12 UTC, re-taro commented
というかcommit messageにできるだけ本文を載せてください。くそでかcommitになるのなら

2022-08-16 17:28 UTC, re-taro requested changes

2022-08-16 17:28 UTC, re-taro commented on front/src/stories/header.stories.tsx
> +export const Default: Story = () => <Header />;
```suggestion
export const Default: Story = {};
```

2022-08-16 17:28 UTC, re-taro commented on front/src/stories/layout.stories.tsx
> +export const Default: Story = () => (
上のexport defaultで制御すべき

```suggestion
export const Default: Story = {};
```

2022-08-16 17:28 UTC, re-taro commented on front/src/stories/layout.stories.tsx
> +
```suggestion
  args: { children: <div>hogehoge</div> }
```

2022-08-16 17:29 UTC, re-taro commented on front/src/components/header.tsx
> +  <header className={`${styles["enshita-header"]} ${styles["enshita-header-pc"]}`}>
これどういうエラーか詳細をここで良いので貼ってください

2022-08-16 17:30 UTC, re-taro commented on front/src/components/header.tsx
> +    <div className={styles["enshita-header-logo"]}>
変更があるように見えないです

2022-08-16 17:31 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="github" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-github"]}`}>GitHub</a>
これどういうエラーか詳細をここで良いので貼ってください

2022-08-16 17:32 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="twitter" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`}>Twitter</a>
これどういうエラーか詳細をここで良いので貼ってください

2022-08-16 17:32 UTC, re-taro commented on front/src/components/footer.tsx
> +            <a href="./" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-homepage"]}`}>Home Page</a>
これどういうエラーか詳細をここで良いので貼ってください

2022-08-16 18:07 UTC, koutyuke commented on front/.eslintrc.yml
> +  import/resolver:
`tsconfig.json` のalias( `"~/*": ["src/*"]` ) を `eslint-import-resolver-typescript` を使って `eslint` に読み込ませるためです。

2022-08-16 18:45 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="twitter" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`}>Twitter</a>
`Curly braces are unnecessary here.`
[[react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)

2022-08-16 18:46 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="twitter" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-twitter"]}`}>Twitter</a>
Curly braces are unnecessary here.
[react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)

2022-08-16 18:49 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="./" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-homepage"]}`}>Home Page</a>
`Curly braces are unnecessary here.`
[react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)

2022-08-16 18:49 UTC, koutyuke commented on front/src/components/footer.tsx
> +            <a href="github" className={`${styles["enshita-footer-link"]} ${styles["enshita-footer-github"]}`}>GitHub</a>
`Curly braces are unnecessary here.`
[react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)

2022-08-16 18:50 UTC, koutyuke commented on front/src/components/header.tsx
> +  <header className={`${styles["enshita-header"]} ${styles["enshita-header-pc"]}`}>
`Curly braces are unnecessary here.`
[react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/jsx-curly-brace-presence.md)

2022-08-16 19:03 UTC, koutyuke commented on front/package.json
> +    "normalize.css": "^8.0.1",
[3c3efa6](https://github.com/Growthers/enshita/pull/49/commits/3c3efa6eda96b3e2a9afd22aeab35bab3562608e)
変更しました

2022-08-16 19:04 UTC, koutyuke commented on front/src/components/footer.tsx
> +          <ul className={styles["enshita-footer-list"]} role="navigation">
[77d4702](https://github.com/Growthers/enshita/pull/49/commits/77d47025dc4e3b4c620abae83d6aa19f6c7772c6)
変更しました。

2022-08-16 19:04 UTC, koutyuke commented on front/src/main.tsx
> +const root = createRoot(container);
[802a2e2](https://github.com/Growthers/enshita/pull/49/commits/802a2e28b5e79c949092932a3adfc0a8d94c338d)
変更しました

2022-08-16 19:05 UTC, koutyuke commented on front/src/main.tsx
> +const root = createRoot(container);
この件で`main.tsx` と `index.html` の変更は削除しますか？

2022-08-16 19:06 UTC, koutyuke commented on front/src/stories/layout.stories.tsx
> +
[4dfddbb](https://github.com/Growthers/enshita/pull/49/commits/4dfddbb58143a7afd8f48b83aefc8e3eafe1a764)
変更しました。

2022-08-16 19:06 UTC, koutyuke commented on front/src/stories/layout.stories.tsx
> +export const Default: Story = () => (
[4dfddbb](https://github.com/Growthers/enshita/pull/49/commits/4dfddbb58143a7afd8f48b83aefc8e3eafe1a764)
削除しました。

2022-08-16 19:06 UTC, koutyuke commented on front/src/stories/header.stories.tsx
> +export const Default: Story = () => <Header />;
[4dfddbb](https://github.com/Growthers/enshita/pull/49/commits/4dfddbb58143a7afd8f48b83aefc8e3eafe1a764)
変更しました。

2022-08-16 19:06 UTC, koutyuke commented on front/src/stories/footer.stories.tsx
> +export const Default: Story = () => <Footer />;
[4dfddbb](https://github.com/Growthers/enshita/pull/49/commits/4dfddbb58143a7afd8f48b83aefc8e3eafe1a764)
変更しました

2022-08-16 19:07 UTC, koutyuke commented on front/src/components/footer.tsx
> +          <div className={`${styles["enshita-footer-logo"]} ${styles["enshita-footer-hidden"]}`}>
[c6f5f26](https://github.com/Growthers/enshita/pull/49/commits/c6f5f266a7c70c16a90cb9600978219fb85a9233)
`p`tagに変更しました

2022-08-16 19:08 UTC, koutyuke commented on front/src/components/header.tsx
> +    <div className={styles["enshita-header-logo"]}>
[c6f5f26](https://github.com/Growthers/enshita/pull/49/commits/c6f5f266a7c70c16a90cb9600978219fb85a9233)
`p`tagに変更しました

2022-08-17 02:37 UTC, re-taro commented on front/src/main.tsx
> +const root = createRoot(container);
しなくて結構です

2022-08-17 02:38 UTC, re-taro commented on front/.eslintrc.yml
> +  import/resolver:
コレなくても読み込まれたと思うんですがダメそうでしょうか？

2022-08-17 04:03 UTC, re-taro commented on front/.eslintrc.yml
> +  import/resolver:
確認しました

2022-08-17 15:33 UTC, re-taro requested changes

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/footer.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
```suggestion
import { ComponentMeta, ComponentStoryObj } from "@storybook/react";
```

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/footer.stories.tsx
> +type Story = ComponentStory<T>;
```suggestion
type Story = ComponentStoryObj<T>;
```

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/header.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
```suggestion
import { ComponentMeta, ComponentStoryObj } from "@storybook/react";
```

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/header.stories.tsx
> +type Story = ComponentStory<T>;
```suggestion
type Story = ComponentStoryObj<T>;
```

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/layout.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
```suggestion
import { ComponentMeta, ComponentStoryObj } from "@storybook/react";
```

2022-08-17 15:33 UTC, re-taro commented on front/src/stories/layout.stories.tsx
> +type Story = ComponentStory<T>;
```suggestion
type Story = ComponentStoryObj<T>;
```

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/layout.stories.tsx
> +type Story = ComponentStory<T>;
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/layout.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/header.stories.tsx
> +type Story = ComponentStory<T>;
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/header.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/footer.stories.tsx
> +type Story = ComponentStory<T>;
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 15:39 UTC, koutyuke commented on front/src/stories/footer.stories.tsx
> +import { ComponentMeta, ComponentStory } from "@storybook/react";
[2968d41](https://github.com/Growthers/enshita/pull/49/commits/2968d411de70be28b0476458be34a372b07846ac)
変更しました。

2022-08-17 16:24 UTC, closed without merging

2022-08-17 16:24 UTC, mirror-kt commented
This PR should be split to specific PRs.