feat() add header
Growthers/enshita pull request #77
Opened 2022-08-17 17:57 UTC by mirror-kt

2022-08-17 18:37 UTC, mirror-kt commented
@koutyuke 
コミットはキレイキレイしたのであとはよしなに実装してください
(1PRでやることは1つに絞ってください。後で詰みます。)

2022-08-19 03:38 UTC, re-taro requested changes
mainの変更をmergeしたらapprove

2022-08-19 09:05 UTC, re-taro approved these changes

2022-08-19 09:07 UTC, Yusuke4869 approved these changes

2022-08-19 09:41 UTC, merged