feat(front): Add footer
Growthers/enshita pull request #78
Opened 2022-08-17 18:22 UTC by mirror-kt

## Issue: https://github.com/Growthers/enshita/issues/28

FYI: https://github.com/Growthers/enshita/pull/49

## What
- フッターの実装

## Requirements
このPRをマージする前に https://github.com/Growthers/enshita/pull/77 がマージされる必要があります。
(必要なフォントが含まれている)

2022-08-20 07:26 UTC, re-taro requested changes

2022-08-20 07:26 UTC, re-taro commented on front/src/components/footer.tsx
> +        <div
こことりあえずpタグ

2022-08-20 07:26 UTC, re-taro commented on front/src/stories/footer.stories.tsx
> +export const Default: Story = () => <Footer />;
```suggestion
export const Default: Story = {};
```

2022-08-20 08:01 UTC, koutyuke commented on front/src/stories/footer.stories.tsx
> +export const Default: Story = () => <Footer />;
[4337bc0](https://github.com/Growthers/enshita/pull/78/commits/4337bc04a0ea4602d2b53e18f42af51717f411ad)
変更しました。

2022-08-20 08:06 UTC, koutyuke commented on front/src/components/footer.tsx
> +        <div
[e22b395](https://github.com/Growthers/enshita/pull/78/commits/e22b3953795ce629f94447cb2b48ae9931034275)

2022-08-20 08:13 UTC, re-taro approved these changes

2022-08-20 08:17 UTC, Yusuke4869 requested changes

2022-08-20 08:17 UTC, Yusuke4869 commented on front/src/styles/footer.module.scss
> +  height: calc(20vh - 20px);
20pxを削除するという話だったと思うので削除お願いします

2022-08-20 08:17 UTC, Yusuke4869 commented on front/src/styles/footer.module.scss
> +    height: calc(15vh - 20px);
ここも同様

2022-08-21 07:22 UTC, Yusuke4869 approved these changes

2022-08-21 07:28 UTC, re-taro approved these changes

2022-08-21 09:05 UTC, merged