fix: corrected automerge in renovate.json to true
Growthers/enshita pull request #96
Opened 2022-08-20 08:35 UTC by Sigumaa

2022-08-20 08:41 UTC, re-taro approved these changes

2022-08-20 09:25 UTC, mirror-kt requested changes
まだ見てないからマージ防止のために一旦RC

2022-08-20 09:29 UTC, mirror-kt requested changes
`packageRules` に以下を追加してください

```yaml
    {
      "matchUpdateTypes": [
        "minor",
        "patch"
      ],
      "automerge": true
    }
```

2022-08-20 09:29 UTC, mirror-kt commented on renovate.json
> +    "automerge": true
```suggestion
```

2022-08-20 09:29 UTC, mirror-kt commented on renovate.json
> +      "automerge": true,
```suggestion
```

2022-08-20 09:29 UTC, mirror-kt commented on renovate.json
> +      "automerge": true,
```suggestion
```

2022-08-20 09:29 UTC, mirror-kt commented on renovate.json
> +      "automerge": true,
```suggestion
```

2022-08-20 16:07 UTC, Sigumaa commented on renovate.json
> +      "automerge": true,
[27b4253](https://github.com/Growthers/enshita/pull/96/commits/27b425352f53edcfaac8a12c418dd5854ab3ae52)

2022-08-20 16:07 UTC, Sigumaa commented on renovate.json
> +      "automerge": true,
[27b4253](https://github.com/Growthers/enshita/pull/96/commits/27b425352f53edcfaac8a12c418dd5854ab3ae52)

2022-08-20 16:07 UTC, Sigumaa commented on renovate.json
> +      "automerge": true,
[27b4253](https://github.com/Growthers/enshita/pull/96/commits/27b425352f53edcfaac8a12c418dd5854ab3ae52)

2022-08-20 16:07 UTC, Sigumaa commented on renovate.json
> +    "automerge": true
[27b4253](https://github.com/Growthers/enshita/pull/96/commits/27b425352f53edcfaac8a12c418dd5854ab3ae52)

2022-08-20 18:06 UTC, mirror-kt requested changes
JSONとして不正です

2022-08-20 18:06 UTC, mirror-kt commented on renovate.json
> +    }
```suggestion
    },
```

2022-08-20 23:13 UTC, Sigumaa commented on renovate.json
> +    }
[a8d752a](https://github.com/Growthers/enshita/pull/96/commits/a8d752a13701574ef96f7f3a6c5a5388d3eff8e5)

2022-08-21 05:40 UTC, mirror-kt approved these changes

2022-08-21 05:44 UTC, re-taro approved these changes

2022-08-21 05:45 UTC, merged